### ISSUE TITLE
Update TODO MVC and Template with new i18n support

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro#156]
- [x] Move po files into a resource path
- [x] Update string extraction helpers (e.g. Makefile) to output to the po dir
- [x] Update server to serve the PO files from the proper query
- [x] Fix the client to use new support, with Yahoo and IBM ICU
- [ ] Possibly use Google Closure's i18n formatting for todo mvc, since it does no SSR...would show alt plugin.

**Comment by awkay** [comment]
I'm updating the template, since it is a full-featured example. Perhaps todomvc can be done later when it goes out of alpha.
